### ISSUE TITLE
herbs1.mzn gives type error

### ISSUE THREAD

**Issue by PerMildner** [MiniZinc/specialization-examples#20]
One of the downloads at [Week 1 of Solving Algorithms ...](https://www.coursera.org/learn/solving-algorithms-discrete-optimization/lecture/0nWyf/3-1-5-search) causes compilation error

For the model [herbs1.mzn](https://github.com/MiniZinc/specialization-examples/blob/fa6d54968ff803db02b2bca1e05187dfbc0cc5b7/CP/search/herbs1.mzn), with MiniZinc 2.7.4 and the default solver Gecode 6.3.0, I get the error message:

```
[stdlib_set:37.1-99](err:/Applications/MiniZincIDE.app/Contents/Resources/share/minizinc/std/stdlib/stdlib_set.mzn?line=37&column=1):
MiniZinc: type error: type-inst variable $T instantiated with different types (set of ELEMENTS vs set of SEASONS)
Process finished with non-zero exit code 1.
```

I have not looked at it, and there are no instructions accompanying the example (or any of the examples?) so I do not know whether this is expected for this model.

**Comment by Dekker1** [comment]
The problem was `(ELEMENTS union SEASONS)` taking the union of two different enumerated types is not correct. What the declaration of the table was actually aiming to do was to convert the enumerated types back into integers to allow them to exist together in the same table. I've adjusted the declaration to do this.

**Comment by Dekker1** [comment]
As an additional note, I'm not fully sure whether this combined table is really correct. Although it now seems to do what was intended, there is the implicit assumption that the first element of `ELEMENTS` is equivalent to the first element of `SEASONS`. This does not seem the intent of the model.

I will consult with Peter and adjust the model if required.

**Comment by Dekker1** [comment]
The model has also been updated to address the issue stated in the previous comment
